---
title: "R for Beginners"
---


An introduction to R written by Dr. Sydney E. Everhart, Nikita Gambhir, and Dr. Zhian N. Kamvar.

## Goals

As a result of taking this workshop you should be able to:

 - find, download, and load necessary packages for analysis
 - load tabular data into R
 - understand the basics of data manipulation in R
 - know what a data frame, vector, and function are
 - summarize data
 - visualize data
 - troubleshoot commmon problems

## Website

This website is meant to serve as a companion to the workshop. The pages located
in the **Workshop** tab are rendered versions of R scripts located in the top 
level of https://github.com/everhartlab/IntroR_Workshop. As the workshop is designed to
be interactive where the participants are given some control over what direction
we should take the analyses, the scripts here are only to serve as guidelines.

These scripts follow these conventions:

 - R code is presented how it would appear in the R console with the first line
   prefixed with `>` and subsequent lines prefixed with `+`. 
 - There will be instances where the command is a `stop()` command. These are
   points in the workshop where we stop the participants and ask them to talk 
   amongst themselves, take a short survey, or find information using R's help
   function.



The website located at https://everhartlab.github.io/IntroR_Workshop/ can be build via 
the `make` program:

```make
make clean # run this to build the site from scratch
make
```

Note: if the README.md is changed, make will force-update the index.Rmd and in
turn force update the corresponding HTML.
